server:
  port: 8000
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

---
spring:
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: spring
    password: bitc5600